# Ryandev
# Nginx, PHP, Composer, MariaDB
version: "3.8"

networks:
  local:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./source:/var/www/html
      - ./configuration/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - local

  php:
    build:
      context: ./configuration/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./source:/var/www/html
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - local

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./source:/var/www/html
      - ./composer:/tmp
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - local

  mariadb:
    image: mariadb:10.7.4
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - local